name: fyp_pawsenvy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  lottie: ^3.3.1
  google_nav_bar: ^5.0.7
  flutter_advanced_drawer: ^1.5.0
  line_icons: ^2.0.3
  smooth_page_indicator: ^1.2.1
  card_swiper: ^3.0.1
  google_fonts: ^6.2.1
  flutter_popup_card: ^0.0.6
  flutter_dotenv: ^5.2.1
  table_calendar: ^3.1.2
  flutter_slidable: ^3.1.1
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
