name: fyp_pawsenvy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  lottie: ^3.3.1
  google_nav_bar: ^5.0.7
  flutter_advanced_drawer: ^1.5.0
  line_icons: ^2.0.3
  smooth_page_indicator: ^1.2.1
  card_swiper: ^3.0.1
  google_fonts: ^6.2.1
  flutter_popup_card: ^0.0.6
  flutter_dotenv: ^5.2.1
  table_calendar: ^3.1.2
  flutter_slidable: ^3.1.1
  go_router: ^16.0.0
  firebase_auth: ^5.6.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.11
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  provider: ^6.1.5
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  image: ^4.1.0
  flutter_stepindicator: ^0.1.7
  flutter_intl_phone_field: ^0.0.7
  flutter_image_compress: ^2.4.0
  awesome_snackbar_content: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
